KERNEL_SRC ?= /lib/modules/$(shell uname -r)/build

M?= $(shell pwd)
KBUILD_OPTIONS += ROOTDIR=$(shell cd $(KERNEL_SRC); readlink -e $(M))
KBUILD_OPTIONS += MODNAME?=wlan_cnss_core_pcie
KBUILD_OPTIONS += WLAN_CNSSCORE=m
KBUILD_OPTIONS += CONFIG_WLAN_CNSS_CORE=y
KBUILD_OPTIONS += CONFIG_CNSS2=y CONFIG_CNSS2_DEBUG=y CONFIG_CNSS2_QMI=y CONFIG_CNSS_ASYNC=y \
			 	  CONFIG_MHI_BUS=y CONFIG_MHI_DEBUG=y \
				  CONFIG_QRTR=y CONFIG_QRTR_MHI=y CONFIG_QCOM_QMI_HELPERS=y \
				  CONFIG_MSM_SUBSYSTEM_RESTART=y \
				  CONFIG_DIAG_CHAR=y CONFIG_DIAGFWD_BRIDGE_CODE=y \
				  CONFIG_PCI_SUSPEND_RESUME=y \
				  
				  
all:
	$(MAKE) -C $(KERNEL_SRC) M=$(shell pwd) modules $(KBUILD_OPTIONS)

modules_install:
	$(MAKE) INSTALL_MOD_STRIP=1 -C $(KERNEL_SRC) M=$(shell pwd) modules_install

clean:
	$(MAKE) -C $(KERNEL_SRC) M=$(PWD) clean
