obj-$(CONFIG_DIAG_CHAR) += diagchar_core.o
obj-$(CONFIG_DIAG_CHAR) += diag_local.o
obj-$(CONFIG_DIAG_CHAR) += diagmem.o
obj-$(CONFIG_DIAG_CHAR) += diagfwd_bridge.o
obj-$(CONFIG_DIAG_CHAR) += diagfwd_mhi.o
